services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend/logs:/app/logs
    environment:
      - MIRAKL_MODE=mock
      - TIPSA_MODE=mock
      - MIRAKL_BASE_URL=http://mock.mirakl
      - TIPSA_BASE_URL=http://mock.tipsa
      - LOG_DIR=/app/logs

  extension:
    build:
      context: ./extension
      dockerfile: Dockerfile
    volumes:
      - ./extension/dist:/app/dist
      - ./extension/out:/app/out